const mongoose = require('mongoose')

// Create URL schema
const urlSchema = new mongoose.Schema({
  urlCode: String, // string generated by shortid ex: LghyMGk8
  longUrl: String, // original url
  shortUrl: String, // short url made with baseURL + urlCode
  date: {
    type: String,
    default: Date.now()
  }
})

module.exports = mongoose.model('Url', urlSchema) // turn into 'urls' db collection